---
- name: Example Ansible playbook for Handlers
  hosts: all
  become: yes
  remote_user: ec2-user
  roles:
    - handlers

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

